# Generated by Django 6.0.3 on 2026-04-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='session_token',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
