# Generated by Django 6.0.3 on 2026-04-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomma', '0002_remove_uploadedfile_session_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
