# Generated by Django 6.0.3 on 2026-04-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomma', '0003_uploadedfile_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='mime_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
