# Generated by Django 6.0.3 on 2026-04-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gomma', '0004_uploadedfile_mime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='stash_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
